project_id = "soynuxsibdlgikbpjipr"

[functions.generate-banner]
verify_jwt = true

[functions.refine-idea]
verify_jwt = true

[functions.generate-business-plan]
verify_jwt = true

[functions.transcribe-voice]
verify_jwt = false

[functions.analyze-product-image]
verify_jwt = true

[functions.generate-logo]
verify_jwt = true

[functions.generate-marketing-content]
verify_jwt = true

[functions.refine-marketing-content]
verify_jwt = true

[functions.search-suppliers]
verify_jwt = true

[functions.geocode-address]
verify_jwt = true

[functions.translate-business-plan]
verify_jwt = true

[functions.generate-mockup]
verify_jwt = true

[functions.generate-scene]
verify_jwt = true

[functions.refine-prompt]
verify_jwt = true

[functions.analyze-financial-strategy]
verify_jwt = true